package constants

const ROLE_PERMISSION_COLLECTION = "RolePermissions"
const USER_COLLECTION = "Users"
const DISH_COLLECTION = "Dishes"
const DISH_VOTE_COLLECTION = "DishVotes"
const INGREDIENT_COLLECTION = "Ingredients"
const CONTACT_COLLECTION = "Contacts"
const REFRESH_TOKEN_BLACK_LIST_COLLECTION = "RefreshTokenBlackList"
const CHAT_MESSAGE_COLLECTION = "ChatMessages"
const CHAT_ROOM_COLLECTION = "ChatRooms"
const USER_LOGIN_TRACKS_COLLECTION = "UserLoginTracks"
const WEBSITE_VISIT_TRACKS_COLLECTION = "WebsiteVisitTracks"
const FEEDBACK_COLLECTION = "Feedbacks"
const USER_FAVORITE_COLLECTION = "UserFavorites"
const USER_SAVED_DISH_COLLECTION = "UserSavedDishes"
const USER_DIETARY_PREFERENCE_COLLECTION = "UserDietaryPreferences"
const USER_DISH_INTERACTION_COLLECTION = "UserDishInteractions"
const DISH_POPULARITY_COLLECTION = "DishPopularities"
const USER_DISH_COLLECTION_COLLECTION = "UserDishCollections"
const FOOD_SHOP_COLLECTION = "FoodShops"
const FOOD_SHOP_DISH_COLLECTION = "FoodShopDishes"
const USER_DISH_LOCATION_COLLECTION = "UserDishLocations"
const NOTIFICATION_COLLECTION = "Notifications"
const NOTIFICATION_PREFERENCE_COLLECTION = "NotificationPreferences"
