package constants

const CREATE_ROLE = "CREATE_ROLE"
const FIND_ALL_ROLE = "FIND_ALL_ROLE"
const FIND_ONE_ROLE = "FIND_ONE_ROLE"
const UPDATE_ROLE = "UPDATE_ROLE"
const REMOVE_ROLE = "REMOVE_ROLE"

const CREATE_USER = "CREATE_USER"
const FIND_ALL_USER = "FIND_ALL_USER"
const FIND_ONE_USER = "FIND_ONE_USER"
const UPDATE_USER = "UPDATE_USER"
const REMOVE_USER = "REMOVE_USER"

const CREATE_DISH = "CREATE_DISH"
const FIND_ALL_DISH = "FIND_ALL_DISH"
const FIND_ONE_DISH = "FIND_ONE_DISH"
const UPDATE_DISH = "UPDATE_DISH"
const REMOVE_DISH = "REMOVE_DISH"
const ANALYZE_DISH = "ANALYZE_DISH"

const CREATE_INGREDIENT = "CREATE_INGREDIENT"
const FIND_ALL_INGREDIENT = "FIND_ALL_INGREDIENT"
const FIND_ONE_INGREDIENT = "FIND_ONE_INGREDIENT"
const UPDATE_INGREDIENT = "UPDATE_INGREDIENT"
const REMOVE_INGREDIENT = "REMOVE_INGREDIENT"

const CREATE_CONTACT = "CREATE_CONTACT"
const FIND_ALL_CONTACT = "FIND_ALL_CONTACT"
const FIND_ONE_CONTACT = "FIND_ONE_CONTACT"
const UPDATE_CONTACT = "UPDATE_CONTACT"
const REMOVE_CONTACT = "REMOVE_CONTACT"

const CREATE_DISH_VOTE = "CREATE_DISH_VOTE"
const FIND_ALL_DISH_VOTE = "FIND_ALL_DISH_VOTE"
const FIND_ONE_DISH_VOTE = "FIND_ONE_DISH_VOTE"
const UPDATE_DISH_VOTE = "UPDATE_DISH_VOTE"
const REMOVE_DISH_VOTE = "REMOVE_DISH_VOTE"

const FIND_USER_LOGIN_TRACK = "FIND_USER_LOGIN_TRACK"
const FIND_ALL_USER_LOGIN_TRACK = "FIND_ALL_USER_LOGIN_TRACK"

const CREATE_WEBSITE_VISIT = "CREATE_WEBSITE_VISIT"
const FIND_ALL_WEBSITE_VISIT = "FIND_ALL_WEBSITE_VISIT"
const FIND_ONE_WEBSITE_VISIT = "FIND_ONE_WEBSITE_VISIT"
const UPDATE_WEBSITE_VISIT = "UPDATE_WEBSITE_VISIT"
const REMOVE_WEBSITE_VISIT = "REMOVE_WEBSITE_VISIT"
