package constants

const CREATE_ROLE = "CREATE_ROLE"
const FIND_ALL_ROLE = "FIND_ALL_ROLE"
const FIND_ONE_ROLE = "FIND_ONE_ROLE"
const UPDATE_ROLE = "UPDATE_ROLE"
const REMOVE_ROLE = "REMOVE_ROLE"

const CREATE_USER = "CREATE_USER"
const FIND_ALL_USER = "FIND_ALL_USER"
const FIND_ONE_USER = "FIND_ONE_USER"
const UPDATE_USER = "UPDATE_USER"
const REMOVE_USER = "REMOVE_USER"
