package constants

const CREATE_ROLE = "CREATE_ROLE"
const FIND_ALL_ROLE = "FIND_ALL_ROLE"
const FIND_ONE_ROLE = "FIND_ONE_ROLE"
const UPDATE_ROLE = "UPDATE_ROLE"
const REMOVE_ROLE = "REMOVE_ROLE"

const CREATE_USER = "CREATE_USER"
const FIND_ALL_USER = "FIND_ALL_USER"
const FIND_ONE_USER = "FIND_ONE_USER"
const UPDATE_USER = "UPDATE_USER"
const REMOVE_USER = "REMOVE_USER"

const CREATE_DISH = "CREATE_DISH"
const FIND_ALL_DISH = "FIND_ALL_DISH"
const FIND_ONE_DISH = "FIND_ONE_DISH"
const UPDATE_DISH = "UPDATE_DISH"
const REMOVE_DISH = "REMOVE_DISH"

const CREATE_INGREDIENT = "CREATE_INGREDIENT"
const FIND_ALL_INGREDIENT = "FIND_ALL_INGREDIENT"
const FIND_ONE_INGREDIENT = "FIND_ONE_INGREDIENT"
const UPDATE_INGREDIENT = "UPDATE_INGREDIENT"
const REMOVE_INGREDIENT = "REMOVE_INGREDIENT"

const CREATE_CONTACT = "CREATE_CONTACT"
const FIND_ALL_CONTACT = "FIND_ALL_CONTACT"
const FIND_ONE_CONTACT = "FIND_ONE_CONTACT"
const UPDATE_CONTACT = "UPDATE_CONTACT"
const REMOVE_CONTACT = "REMOVE_CONTACT"
