services:
  what-to-eat-api:
    image: fxanhkhoa/what-to-eat-api:latest
    container_name: what-to-eat-api
    restart: always
    env_file:
      - .env
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.what-to-eat-api.rule=Host(`api.eatwhat.io.vn`)"
      - "traefik.http.routers.what-to-eat-api.entrypoints=websecure"
      - "traefik.http.routers.what-to-eat-api.tls=true"
      - "traefik.http.services.what-to-eat-api.loadbalancer.server.port=5099"

networks:
  traefik-public:
    external: true
