// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
	"time"
)

type CreateIngredientInput struct {
	Slug               string                `json:"slug" bson:"slug"`
	Title              []*MultiLanguageInput `json:"title,omitempty" bson:"title"`
	Measure            *string               `json:"measure,omitempty" bson:"measure"`
	Calories           *int                  `json:"calories,omitempty" bson:"calories"`
	Carbohydrate       *int                  `json:"carbohydrate,omitempty" bson:"carbohydrate"`
	Fat                *int                  `json:"fat,omitempty" bson:"fat"`
	IngredientCategory *string               `json:"ingredientCategory,omitempty" bson:"ingredientCategory"`
	Weight             *int                  `json:"weight,omitempty" bson:"weight"`
	Protein            *int                  `json:"protein,omitempty" bson:"protein"`
	Cholesterol        *int                  `json:"cholesterol,omitempty" bson:"cholesterol"`
	Sodium             *int                  `json:"sodium,omitempty" bson:"sodium"`
}

type CreateUserInput struct {
	Email       string  `json:"email" bson:"email"`
	Password    *string `json:"password,omitempty" bson:"password"`
	Name        *string `json:"name,omitempty" bson:"name"`
	DateOfBirth *string `json:"dateOfBirth,omitempty" bson:"dateOfBirth"`
	Address     *string `json:"address,omitempty" bson:"address"`
	Phone       *string `json:"phone,omitempty" bson:"phone"`
	GoogleID    *string `json:"googleID,omitempty" bson:"googleID"`
	FacebookID  *string `json:"facebookID,omitempty" bson:"facebookID"`
	GithubID    *string `json:"githubID,omitempty" bson:"githubID"`
	Avatar      *string `json:"avatar,omitempty" bson:"avatar"`
}

type Ingredient struct {
	Slug               string           `json:"slug" bson:"slug"`
	Title              []*MultiLanguage `json:"title,omitempty" bson:"title"`
	Measure            *string          `json:"measure,omitempty" bson:"measure"`
	Calories           *int             `json:"calories,omitempty" bson:"calories"`
	Carbohydrate       *int             `json:"carbohydrate,omitempty" bson:"carbohydrate"`
	Fat                *int             `json:"fat,omitempty" bson:"fat"`
	IngredientCategory *string          `json:"ingredientCategory,omitempty" bson:"ingredientCategory"`
	Weight             *int             `json:"weight,omitempty" bson:"weight"`
	Protein            *int             `json:"protein,omitempty" bson:"protein"`
	Cholesterol        *int             `json:"cholesterol,omitempty" bson:"cholesterol"`
	Sodium             *int             `json:"sodium,omitempty" bson:"sodium"`
	Deleted            bool             `json:"deleted" bson:"deleted"`
	DeletedAt          *time.Time       `json:"deletedAt,omitempty" bson:"deletedAt"`
	DeletedBy          *string          `json:"deletedBy,omitempty" bson:"deletedBy"`
	UpdatedAt          *time.Time       `json:"updatedAt,omitempty" bson:"updatedAt"`
	UpdatedBy          *string          `json:"updatedBy,omitempty" bson:"updatedBy"`
	CreatedAt          *time.Time       `json:"createdAt,omitempty" bson:"createdAt"`
	CreatedBy          *string          `json:"createdBy,omitempty" bson:"createdBy"`
	ID                 string           `json:"_id" bson:"_id,omitempty"`
}

type LoginInput struct {
	Token string `json:"token" bson:"token"`
}

type MultiLanguage struct {
	Language string  `json:"language" bson:"language"`
	Data     *string `json:"data,omitempty" bson:"data"`
}

type MultiLanguageInput struct {
	Language string  `json:"language" bson:"language"`
	Data     *string `json:"data,omitempty" bson:"data"`
}

type RetrieveTokenInput struct {
	RefreshToken string `json:"refreshToken" bson:"refreshToken"`
}

type TokenResult struct {
	Token        string `json:"token" bson:"token"`
	RefreshToken string `json:"refreshToken" bson:"refreshToken"`
}

type UpdateIngredientInput struct {
	Slug               string                `json:"slug" bson:"slug"`
	Title              []*MultiLanguageInput `json:"title,omitempty" bson:"title"`
	Measure            *string               `json:"measure,omitempty" bson:"measure"`
	Calories           *int                  `json:"calories,omitempty" bson:"calories"`
	Carbohydrate       *int                  `json:"carbohydrate,omitempty" bson:"carbohydrate"`
	Fat                *int                  `json:"fat,omitempty" bson:"fat"`
	IngredientCategory *string               `json:"ingredientCategory,omitempty" bson:"ingredientCategory"`
	Weight             *int                  `json:"weight,omitempty" bson:"weight"`
	Protein            *int                  `json:"protein,omitempty" bson:"protein"`
	Cholesterol        *int                  `json:"cholesterol,omitempty" bson:"cholesterol"`
	Sodium             *int                  `json:"sodium,omitempty" bson:"sodium"`
}

type UpdateUserInput struct {
	ID          string  `json:"id" bson:"id"`
	Email       string  `json:"email" bson:"email"`
	Name        *string `json:"name,omitempty" bson:"name"`
	DateOfBirth *string `json:"dateOfBirth,omitempty" bson:"dateOfBirth"`
	Address     *string `json:"address,omitempty" bson:"address"`
	Phone       *string `json:"phone,omitempty" bson:"phone"`
	GoogleID    *string `json:"googleID,omitempty" bson:"googleID"`
	FacebookID  *string `json:"facebookID,omitempty" bson:"facebookID"`
	GithubID    *string `json:"githubID,omitempty" bson:"githubID"`
	Avatar      *string `json:"avatar,omitempty" bson:"avatar"`
}

type User struct {
	Email       string     `json:"email" bson:"email"`
	Password    *string    `json:"password,omitempty" bson:"password"`
	Name        *string    `json:"name,omitempty" bson:"name"`
	DateOfBirth *time.Time `json:"dateOfBirth,omitempty" bson:"dateOfBirth"`
	Address     *string    `json:"address,omitempty" bson:"address"`
	Phone       *string    `json:"phone,omitempty" bson:"phone"`
	GoogleID    *string    `json:"googleID,omitempty" bson:"googleID"`
	FacebookID  *string    `json:"facebookID,omitempty" bson:"facebookID"`
	GithubID    *string    `json:"githubID,omitempty" bson:"githubID"`
	Avatar      *string    `json:"avatar,omitempty" bson:"avatar"`
	Deleted     bool       `json:"deleted" bson:"deleted"`
	DeletedAt   *time.Time `json:"deletedAt,omitempty" bson:"deletedAt"`
	DeletedBy   *string    `json:"deletedBy,omitempty" bson:"deletedBy"`
	UpdatedAt   *time.Time `json:"updatedAt,omitempty" bson:"updatedAt"`
	UpdatedBy   *string    `json:"updatedBy,omitempty" bson:"updatedBy"`
	CreatedAt   *time.Time `json:"createdAt,omitempty" bson:"createdAt"`
	CreatedBy   *string    `json:"createdBy,omitempty" bson:"createdBy"`
	ID          string     `json:"_id" bson:"_id,omitempty"`
	RoleName    string     `json:"roleName" bson:"roleName"`
}

type Role string

const (
	RoleAdmin Role = "ADMIN"
	RoleUser  Role = "USER"
)

var AllRole = []Role{
	RoleAdmin,
	RoleUser,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleAdmin, RoleUser:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
